src/Entity/Motiv.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\MotivRepository")
 */
class Motiv
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $user_id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $subtitle;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_description;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $seo_url;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $public_hash;

    /**
     * @ORM\Column(type="boolean")
     */
    private $public;

    /**
     * @var string $file Only for Upload files. No Entrys in Database
     */
    private $file;

    /**
     * @var ArrayCollection
     */
    private $images;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updated;

    public function __construct()
    {
        $this->images = new ArrayCollection();
    }

    /**
     * @return Collection|Images[]
     */
    public function getImages(): Array
    {
        return $this->images;
    }

    public function setImages(array $images): self
    {
        $this->images = $images;

        return $this;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->user_id;
    }

    public function setUserId(int $user_id): self
    {
        $this->user_id = $user_id;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSubtitle(): ?string
    {
        return $this->subtitle;
    }

    public function setSubtitle(?string $subtitle): self
    {
        $this->subtitle = $subtitle;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSeoTitle(): ?string
    {
        return $this->seo_title;
    }

    public function setSeoTitle(?string $seo_title): self
    {
        $this->seo_title = $seo_title;

        return $this;
    }

    public function getSeoDescription(): ?string
    {
        return $this->seo_description;
    }

    public function setSeoDescription(?string $seo_description): self
    {
        $this->seo_description = $seo_description;

        return $this;
    }

    public function getSeoUrl(): ?string
    {
        return $this->seo_url;
    }

    public function setSeoUrl(?string $seo_url): self
    {
        $this->seo_url = $seo_url;

        return $this;
    }

    public function getPublicHash(): ?string
    {
        return $this->public_hash;
    }

    public function setPublicHash(string $public_hash): self
    {
        $this->public_hash = $public_hash;

        return $this;
    }

    public function getPublic(): ?bool
    {
        return $this->public;
    }

    public function setPublic(bool $public): self
    {
        $this->public = $public;

        return $this;
    }

    /**
     * @return string
     */
    public function getFile(): ?string
    {
        return $this->file;
    }

    /**
     * @param string $file
     */
    public function setFile(string $file): self
    {
        $this->file = $file;
    }

    /**
     * @return mixed
     */
    public function getUpdated()
    {
        return $this->updated;
    }

    /**
     * @param mixed $updated
     */
    public function setUpdated($updated): void
    {
        $this->updated = $updated;
    }


}

src/Form/MotivType.php
<?php

namespace App\Form;

use App\Entity\Motiv;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\File;


class MotivType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titel',
                'required' => true
            ])
            ->add('subtitle', TextType::class, [
                'label' => 'Zusatzbezeichnung',
                'required' => false
            ])
            ->add('description', TextareaType::class, [
                'label' => 'Motivbeschreibung',
                'required' => false,
                'attr' => [
                    'rows' => '6',
                ]
            ])
            ->add('seo_title', TextType::class, [
                'label' => 'SEO-Titel (wenn frei gelassen, wird der Motiv-Titel dafür verwendet)',
                'required' => false
            ])
            ->add('seo_description', TextType::class, [
                'label' => 'SEO-Beschreibungstext (optional)',
                'required' => false
            ])
            ->add('seo_url', TextType::class, [
                'label' => 'SEO-Url (wenn frei gelassen, wird der Motiv-Titel dafür verwendet)',
                'required' => false
            ])
            ->add('public', ChoiceType::class, [
                'label' => 'Motiv online?',
                'required' => true,
                'multiple' => false,
                'expanded' => false,
                'choices' => [
                    'Offline' => 0,
                    'Online' => 1
                ]
            ])
            ->add('file', FileType::class, [
                'label' => 'Image-Upload (jpg, png)',
                'mapped' => false,
                'required' => false,
                'constraints' => [
                    new File([
                        'maxSize' => '1024k',
                        'mimeTypes' => [
                            'image/jpeg',
                            'image/png',
                        ],
                        'mimeTypesMessage' => 'Please upload a valid Jpg or Png Image',
                    ])
                ]
            ])
            ->add('images', CollectionType::class, [
                'label' => false,
                'entry_type' => ImageType::class,
                'entry_options' => ['label' => false],
            ])
            ->add('submit', SubmitType::class, [
                'label' => 'Speichern'
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Motiv::class,
        ]);
    }
}

src/Controller/MotivController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;

use App\Entity\Motiv;
use App\Form\MotivType;
use App\Utils\MotivHelper;

use App\Entity\Images;
use App\Form\ImageSelectionType;
use App\Form\TitleImageSelectionType;

class MotivController extends AbstractController
{
    /**
     * @var MotivHelper
     */
    private $motivHelper;

    /**
     * @var FlashBagInterface
     */
    private $flashBag;

    /**
     * MotivController constructor.
     * @param MotivHelper $motivHelper
     * @param FlashBagInterface $flashBag
     */
    public function __construct(MotivHelper $motivHelper, FlashBagInterface $flashBag)
    {
        $this->userId = 1;
        $this->motivHelper = $motivHelper;
        $this->flashBag = $flashBag;
    }

    /**
     * @Route("/motive", name="motive_show")
     * @return Response
     */
    public function index()
    {
        $motive = $this->getDoctrine()->getRepository(Motiv::class)->findBy(array('user_id' => $this->userId), array('id' => 'DESC'));
        foreach($motive AS $key => $motiv){
            $images = $this->getDoctrine()->getRepository(Images::class)->findBy(array('motiv' => $motiv));
            $motive[$key]->setImages($images);
        }

        return $this->render('motiv/index.html.twig',[
            'motive' => $motive
        ]);
    }

    /**
     * @Route("/motive/create", name="motiv_create")
     * @param Request $request
     * @return Response
     */
    public function new(Request $request)
    {
        // New Motiv
        $motiv = new Motiv;
        $motiv->setImages([]);

        // Make Form for Motiv
        $form = $this->createForm(MotivType::class, $motiv);

        // Handle Request of Form Motiv
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // set UserId in Entity Motiv
            $motiv->setUserId($this->userId);

            // generate Public Hash by title and datetime
            $publicHash = hash('ripemd160', $form['title']->getData().date('YmdHis'));

            // set Public Hash in Entity Motiv
            $motiv->setPublicHash($publicHash);

            // generate and check URL and save in Entity Motiv
            $url = $this->motivHelper->generate_and_check_url_if_its_unique(
                $motiv->getSeoUrl(),
                $publicHash,
                $motiv->getTitle()
            );

            // save URL in Motiv
            $motiv->setSeoUrl($url);

            // set actually DateTime
            $motiv->setUpdated(new \DateTime());

            // Add new Entry in Database
            $em = $this->getDoctrine()->getManager();
            $em->persist($motiv);
            $em->flush();

            // Upload File and store in Database
            $this->motivHelper->uploadMotivImage(
                $form['file']->getData(),
                $motiv,
                $this->getParameter('upload_folder')
            );

            // create Flashbag Message for User
            $this->flashBag->add('notice', 'Motiv was successfull created!');

            return $this->redirectToRoute('motiv_edit', ['publicHash' => $publicHash]);
        }

        return $this->render('motiv/new.html.twig',[
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/motive/{publicHash}", name="motiv_edit")
     * @return Response
     */
    public function edit($publicHash, Request $request)
    {
        // get Motiv by UserId and MotivId
        $motiv = $this->getDoctrine()->getRepository(Motiv::class)
            ->findOneBy([
                'public_hash' => $publicHash,
                'user_id' => $this->userId
            ]);

        // If nothing find, redirect back
        if(!$motiv){ return $this->redirectToRoute('motive_show'); }

        // get the actually Url for detect changes after submit
        $oldUrl = $motiv->getSeoUrl();

        // set Public Hash in Entity Motiv
        $publicHash = $motiv->getPublicHash();

        $images = $this->getDoctrine()->getRepository(Images::class)->findBy(['motiv' => $motiv]);
        $motiv->setImages($images);
        //dump($motiv);

        // Make Form for Motiv
        $form = $this->createForm(MotivType::class, $motiv);

        // Handle Request of Form Motiv
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            // generate and/or check URL
            $url = $this->motivHelper->generate_and_check_url_if_its_unique(
                $motiv->getSeoUrl(),
                $publicHash,
                $motiv->getTitle()
            );

            // save URL in Motiv
            $motiv->setSeoUrl($url);

            // set actually DateTime
            $motiv->setUpdated(new \DateTime());

            // Save Motiv in Database
            $em = $this->getDoctrine()->getManager();
            $em->persist($motiv);
            $em->flush();

            // Upload File and save in Database
            $this->motivHelper->uploadMotivImage(
                $form['file']->getData(),
                $motiv,
                $this->getParameter('upload_folder')
            );


            // create Flashbag Message for User
            $this->flashBag->add('notice', 'Motiv was successfull changed!');

            // redirect to refresh all Data and Images
            return $this->redirectToRoute('motiv_edit', ['publicHash' => $publicHash]);
        }

        // get all Images from Motiv
        $files = $this->motivHelper->getImageFiles($this->getParameter('upload_folder'), $motiv);

        return $this->render('motiv/edit.html.twig',[
            'form' => $form->createView(),
            'files' => $files,
        ]);
    }
}

templates/motiv/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motive{% endblock %}

{% block body %}
    <h1>Motiv editieren</h1>
    <a href="{{ path('motive_show') }}" class="btn btn-secondary mb-3">Übersicht</a>

    {% for message in app.flashes('notice') %}
        <div class="alert alert-success">{{ message }}</div>
    {% endfor %}

    {{ form_start(form) }}
    {{ form_row(form.title) }}
    {{ form_row(form.subtitle) }}
    {{ form_row(form.description) }}
    {{ form_row(form.seo_title) }}
    {{ form_row(form.seo_description) }}
    {{ form_row(form.seo_url) }}
    {{ form_row(form.public) }}
    <label for="file">Image-Upload (jpg, png)</label>
    {{ form_widget(form.file, {'attr': {'class': 'form-control file'}}) }}

    <button type="submit" class="btn btn-primary mt-3">Speichern</button>

    <h5 class="mt-3 mb-3">Motivbilder verwalten:</h5>
    {% for image in form.images %}
        {% set id = image.vars.value.id %}
        {% if files is defined and files[id] is defined %}
            <a href="{{ files[id].url }}" target="_blank" class="btn-link btn-block mt-2 mb-0">
                <img src="{{ files[id].url }}" alt="{{ files[id].name }}" class="img-thumbnail mr-3" width="100">{{ files[id].name }}
            </a>
        {% endif %}
        {{ form_row(image.id, {'attr': {'class': 'hidden'}}) }}
        {{ form_row(image.filename, {'attr': {'class': 'hidden'}}) }}
        {{ form_row(image.type) }}
        <hr>
    {% endfor %}

    {{ form_end(form) }}
{% endblock %}

templates/motiv/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motive{% endblock %}

{% block body %}
    <h1>Motive</h1>
    <p>User ID is fixed by: <b>1</b></p>
    <a href="{{ path('motiv_create') }}" class="btn btn-primary mb-3">New Motiv</a>
    <table class="table table-striped">
        <tr>
            <th></th>
            <th>Id:</th>
            <th>Titel:</th>
            <th>Subtitel:</th>
            <th>SEO-Url:</th>
            <th>Public Hash:</th>
            <th class="text-right">Online:</th>
            <th class="text-right">Updated:</th>
        </tr>
        {% if motive is defined %}
            {% for motiv in motive %}
                <tr>
                    <td>
                        <a href="{{ path('motiv_edit', {'publicHash': motiv.publicHash}) }}" class="btn btn-primary btn-sm">Edit</a>
                    </td>
                    <td>{{ motiv.id }}</td>
                    <td>{{ motiv.title }}</td>
                    <td>{{ motiv.subtitle }}</td>
                    <td>{{ motiv.seoUrl }}</td>
                    <td>{{ motiv.publicHash }}</td>
                    <td class="text-right">
                        {% if motiv.public == true %}
                            <span class="text-primary">Aktiv</span>
                        {% else %}
                            <span class="text-danger">Gesperrt</span>
                        {% endif %}
                    </td>
                    <td class="text-right">{{ motiv.updated|date('d.m.Y H:i:s') }}</td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>
{% endblock %}

templates/motiv/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Motive{% endblock %}

{% block body %}
    <h1>Motiv create</h1>
    <a href="{{ path('motive_show') }}" class="btn btn-secondary mb-3">Übersicht</a>

    {{ form(form) }}
{% endblock %}